name: '"Configure Namespace Cloud" Action For GitHub Actions'
description: "Configure a Namespace Instance with a Kubernetes cluster and expose a preconfigured kubectl to access it"

inputs:
  preview:
    description: "If set to 'true', the instance created will NOT be destroyed at the end."
    required: false
    default: "false"
  wait-kube-system:
    description: "If set to 'true', wait for coredns and local-path-provisioner to be ready."
    required: false
    default: "true"
  platform:
    description: "Select the platform to run on. Valid options: linux/amd64,linux/arm64,macos/arm64"
    required: false
    default: "linux/amd64"
  machine-shape:
    description: "Specify the machine shape as <cpu>x<mem>. E.g. 2x8 starts a 2 vCPU 8GB RAM instance."
    required: false
    default: "4x8"
  duration:
    description: "If set, specifies how long the instance should live for. E.g. 10m."
    required: false
    default: ""
  unique-tag:
    description: "If set, assign a unique tag to the instance. If there is already an instance with this tag, reuse it."
    required: false
    default: ""
  ingress:
    description: "If set, configures the ingress of this instance. Valid options: wildcard."
    required: false
    default: ""
  kube-version:
    description: "Which Kubernetes cluster version to deploy in the instance. Valid options: 1.26, 1.27, 1.28, 1.29, 1.30, 1.31"
    required: false
    default: "1.26"

outputs:
  registry-address:
    description: "Endpoint address of the registry set up for the Namespace Cloud cluster."
  instance-id:
    description: "Identifier of the Namespace instance hosting the created cluster."
  instance-url:
    description: "Namespace App URL to manage and observe the created instance."
  kubeconfig:
    description: "Plain text version of the kubeconfig used to access the Kubernetes cluster."

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
