name: manual testing
on:
  workflow_dispatch

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  run_nscloud_action:
    runs-on: nscloud-ubuntu-22.04-amd64-2x8
    name: Create a kubernetes cluster
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Cluster
        uses: ./ # Uses an action in the root directory
        id: create-cluster
        with:
          kubernetes-version: "1.30" # Quotation to force the trailing zero.

      - name: Print registry
        run: |
          echo "${{ steps.create-cluster.outputs.registry-address }}"

      - name: Breakpoint
        if: always()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 15m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo
